---
 - name: install/uninstall sw applications
   hosts: all
   vars: 
    - a: tomcat9
    - b: present
    - c: no
   tasks: 
    - name: install/uninstall
      apt: 
       name: "{{a}}"
       state: "{{b}}"
       update_cache: "{{c}}"
...       
