---
 - name: create user using host scope varaibles
   hosts: webserver
   tasks: 
    - name: create user
      user: 
       name: "{{a}}"
       password: "{{b}}"
       uid: "{{c}}"
       home: "{{d}}"
       shell: "{{e}}"
...       
